version: '2'
services:
  nginx-proxy:
    network_mode: 'bridge'
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

  letsencrypt-nginx-proxy-companion:
    network_mode: 'bridge'
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    volumes_from:
      - nginx-proxy:rw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  local-eple-local:
    network_mode: 'bridge'
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=local.eple.local

  local-eple-me:
    network_mode: 'bridge'
    image: jwilder/whoami
    # ports:
    #   - "43210:80"
    environment:
      - VIRTUAL_HOST=local.eple.me
      - LETSENCRYPT_HOST=local.eple.me
      - LETSENCRYPT_EMAIL=havard.ranum@gmail.com

  m24-eple-me:
    network_mode: 'bridge'
    image: nginx:latest
    volumes:
      - ./conf:/etc/nginx/conf.d
    environment:
      - VIRTUAL_HOST=m24.eple.me
      - LETSENCRYPT_HOST=m24.eple.me
      - LETSENCRYPT_EMAIL=havard.ranum@gmail.com

  eple-m24-eple-me:
    network_mode: 'bridge'
    image: nginx:latest
    volumes:
      - ./eple:/etc/nginx/conf.d
    environment:
      - VIRTUAL_HOST=eple.m24.eple.me
      - LETSENCRYPT_HOST=eple.m24.eple.me
      - LETSENCRYPT_EMAIL=havard.ranum@gmail.com
      - VIRTUAL_HOST=whoami.local
