version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # whoami:
  #   image: jwilder/whoami
  #   environment:
  #     - VIRTUAL_HOST=whoami.local


  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    volumes_from:
      - nginx-proxy:rw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # test:
  #   image: jwilder/whoami
  #   environment:
  #     - VIRTUAL_HOST=m24.eple.me
  #     - LETSENCRYPT_HOST=m24.eple.me
  #     - LETSENCRYPT_EMAIL=havard.ranum@gmail.com

  m24proxy:
    image: nginx:latest
    volumes:
      - ./conf:/etc/nginx/conf.d
    environment:
      - VIRTUAL_HOST=m24.eple.me
      - LETSENCRYPT_HOST=m24.eple.me
      - LETSENCRYPT_EMAIL=havard.ranum@gmail.com

  m24-eple:
    image: nginx:latest
    volumes:
      - ./eple:/etc/nginx/conf.d
    environment:
      - VIRTUAL_HOST=eple.m24.eple.me
      - LETSENCRYPT_HOST=eple.m24.eple.me
      - LETSENCRYPT_EMAIL=havard.ranum@gmail.com
