version: '2'
services:
  nginx-proxy:
    network_mode: 'bridge'
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

  whoami:
    network_mode: 'bridge'
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
